model:
  model_name: "facebook/bart-base"

data:
  name: "meetingbank"
  path: "data/meetingbank"
  text_column: "dialogue"      # Change as per dataset column name
  summary_column: "summary"

preprocess:
  max_input_length: 1024
  max_target_length: 256

training_args:
  output_dir: "saved_models/bart_base"
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  num_train_epochs: 3
  learning_rate: 3e-05
  fp16: True
  logging_steps: 50
  save_steps: 500
  eval_steps: 500
  evaluation_strategy: "steps"
  load_best_model_at_end: True
  metric_for_best_model: "eval_rougeL"
  greater_is_better: True
  gradient_accumulation_steps: 1
  seed: 42
